//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ Compatible
// This file is automatically generated by RisohEditor 5.8.1.
// recorder.rc

#define IDC_RECORD                          100
#define IDC_SEND_TO_WHISPER                 101
#define IDC_MESSAGES                        102
#define IDC_EMACS_EVAL                      103
#define IDC_EMACS_COMMAND_EDIT              104
#define IDC_USE_TEST_TEXT                   105
#define IDC_SETTINGS                        106
#define IDC_OPENAI_TOKEN                    107
#define IDC_RADIO_OPENAI                    108
#define IDC_RADIO_CUSTOM                    109
#define IDC_ENDPOINT                        110

#define IDD_RECORDER                        100
#define IDD_SETTINGS                        101

#define IDAPPLY                             1002

#define IDI_RECORDER                        200
#define ID_TRAYICON                         1001

#ifdef APSTUDIO_INVOKED
    #ifndef APSTUDIO_READONLY_SYMBOLS
        #define _APS_NO_MFC                 1
        #define _APS_NEXT_RESOURCE_VALUE    100
        #define _APS_NEXT_COMMAND_VALUE     100
        #define _APS_NEXT_CONTROL_VALUE     1000
        #define _APS_NEXT_SYMED_VALUE       300
    #endif
#endif
